[workspace]

members = [
        "swipl-info",
        "swipl-fli",
        "swipl-macros-parse",
        "swipl-macros",
        "swipl",
        "cargo-swipl",
        "examples/swipl-module-example",
        "examples/binary-example"
]