name: Build and test

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash


env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
          - os: macos-latest
            dmg: no
          - os: macos-latest
            dmg: yes
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install SWI Prolog on Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt-get update
        sudo apt install swi-prolog-nox
    - name: Install LLVM and SWI Prolog on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: choco install llvm swi-prolog
    - name: Install SWI Prolog on MacOS from brew
      if: ${{ matrix.os == 'macos-latest' && matrix.dmg == 'no' }}
      run: brew install swi-prolog
    - name: Install SWI Prolog on MacOS from dmg
      if: ${{ matrix.os == 'macos-latest' && matrix.dmg == 'yes' }}
      run: bash .ci/install_swipl_dmg.sh
    - name: Install cargo-swipl
      run: cargo install --path ./cargo-swipl
    - name: Run tests on posix
      if: ${{ matrix.os != 'windows-latest' }}
      run: cargo swipl test
    - name: Run tests on windows
      if: ${{ matrix.os == 'windows-latest' }}
      env:
        SWIPL: C:\Program Files\swipl\bin\swipl.exe
        LIBCLANG_PATH: C:\Program Files\LLVM\bin\
      run: cargo swipl test
